on: [workflow_dispatch]

jobs:
  runit:
    runs-on: ubuntu-latest
    name: buh
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: ngrok
      run: echo ngrok authtoken $NGROK > ngrok.txt
    - name: buh
      uses: ./
