on: [workflow_dispatch]

jobs:
  runit:
    runs-on: ubuntu-latest
    name: buh
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: buh
      id: buh
      uses: ./
      env:
        NGROK: ${{ secrets.NGROK }}
